name: jenkins-benchmark
on:
  push:
    branches: [mainxx]

jobs:
  jenkins-benchmark:
    name: Jenkins Benchmark
    runs-on: ubuntu-latest
    env:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: cd jenkins && npm i
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      - name: Run Dagger pipeline - Control build
        run: cd jenkins && dagger run node index.js
        env:
          CACHE: all
      - name: Run Dagger pipeline - NO CACHE
        run: cd jenkins && dagger run node index.js
        env:
          CACHE: none
      - name: Run Dagger pipeline - VOLUMES ONLY CACHE
        run: cd jenkins && dagger run node index.js
        env:
          CACHE: volume
      - name: Run Dagger pipeline - LAYERS ONLY CACHE
        run: cd jenkins && dagger run node index.js
        env:
          CACHE: layers
      - name: Run Dagger pipeline - FULL CACHE
        run: cd jenkins && dagger run node index.js
        env:
          CACHE: all
      - name: Cleanup Benchmark
        run: docker stop $(docker ps -aq)
